import { Check, Clock3, DollarSign, ShieldCheck, UserX, X } from "lucide-react";
import { useEffect, useState } from "react";
import { apiUrl } from "./page-api";

async function adminRequest<T>(path:string,token:string,options:any={}):Promise<T>{
 const r=await fetch(apiUrl(path),{method:options.method||"GET",headers:{Authorization:"Bearer "+token,...(options.body?{"Content-Type":"application/json"}:{})},body:options.body?JSON.stringify(options.body):undefined});
 const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||"Admin request failed.");return p;
}
export default function AdminSellers({token,onNotice,onError}:{token:string;onNotice:(s:string)=>void;onError:(s:string)=>void}){
 const [apps,setApps]=useState<any[]>([]),[sellers,setSellers]=useState<any[]>([]),[withdrawals,setWithdrawals]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{const [a,s,w]=await Promise.all([adminRequest<any>("/api/admin/seller-applications",token),adminRequest<any>("/api/admin/sellers",token),adminRequest<any>("/api/admin/seller-withdrawals",token)]);setApps(a.data||[]);setSellers(s.data||[]);setWithdrawals(w.data||[])}catch(e:any){onError(e?.message||"Seller data could not be loaded.")}finally{setLoading(false)}};
 useEffect(()=>{if(token) void load()},[token]);
 const reviewWithdrawal=async(id:number,status:"approved"|"declined"|"paid")=>{setBusy(true);try{await adminRequest("/api/admin/seller-withdrawals/"+id,token,{method:"PATCH",body:{status}});onNotice(status==="paid"?"Withdrawal marked paid.":status==="approved"?"Withdrawal approved for payout.":"Withdrawal declined and funds refunded.");await load()}catch(e:any){onError(e?.message||"Withdrawal update failed.")}finally{setBusy(false)}};
 const review=async(id:number,status:"approved"|"declined"|"reviewing")=>{setBusy(true);try{await adminRequest("/api/admin/seller-applications/"+id,token,{method:"PATCH",body:{status}});setSelected(null);onNotice(status==="approved"?"Seller approved and access granted.":status==="declined"?"Seller application declined.":"Application moved to review.");await load()}catch(e:any){onError(e?.message||"Seller review failed.")}finally{setBusy(false)}};
 const dismissSeller=async(s:any)=>{const confirmed=window.confirm(`Dismiss ${s.sellerName} from approved sellers? Their seller access will be removed. This does not delete their account.`);if(!confirmed)return;const note=window.prompt("Optional reason for dismissing this seller:")||"";setBusy(true);try{await adminRequest("/api/admin/sellers/"+s.userId+"/dismiss",token,{method:"PATCH",body:{adminNote:note}});onNotice("Seller dismissed and seller access removed.");await load()}catch(e:any){onError(e?.message||"Seller dismissal failed.")}finally{setBusy(false)}};
 return <section className="admin-section">
  {selected&&<div className="admin-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="cp-card cp-card-pad admin-detail-modal"><div className="admin-panel-head"><div><span className="cp-kicker">SELLER APPLICATION</span><h2>{selected.sellerName}</h2><p>{selected.email} · User #{selected.userId}</p></div><button className="admin-btn admin-btn-soft" onClick={()=>setSelected(null)}><X size={15}/></button></div><div className="admin-detail-facts"><span><small>Status</small><b>{selected.status}</b></span><span><small>KYC</small><b>{selected.kycStatus} · L{selected.kycLevel??0}</b></span><span><small>Legal name</small><b>{selected.legalName}</b></span><span><small>Phone</small><b>{selected.phone}</b></span><span><small>Country</small><b>{selected.country}</b></span><span><small>Address</small><b>{selected.address}</b></span><span><small>Account source</small><b>{selected.accountSource}</b></span><span><small>Experience</small><b>{selected.experience||"—"}</b></span><span><small>Application IP</small><b className="admin-mono">{selected.applicationIp||"—"}</b></span><span><small>Device / browser</small><b>{selected.userAgent||"—"}</b></span><span><small>Submitted</small><b>{new Date(selected.createdAt).toLocaleString()}</b></span></div><div className="admin-actions" style={{justifyContent:"flex-end",marginTop:18}}><button className="admin-btn admin-btn-soft" disabled={busy} onClick={()=>void review(selected.id,"reviewing")}><Clock3 size={14}/> Reviewing</button><button className="admin-btn admin-btn-danger" disabled={busy} onClick={()=>void review(selected.id,"declined")}><UserX size={14}/> Decline</button><button className="admin-btn admin-btn-primary" disabled={busy} onClick={()=>void review(selected.id,"approved")}><Check size={14}/> Approve seller</button></div></section></div>}
  <div className="admin-grid-two"><section className="cp-card cp-card-pad"><div className="admin-card-title"><div><span className="cp-kicker">SELLER QUEUE</span><h2>Applications</h2><p>KYC-verified users requesting marketplace selling access.</p></div><ShieldCheck size={20}/></div>{loading?<div className="admin-empty">Loading seller applications…</div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Applicant</th><th>KYC</th><th>Status</th><th>Submitted</th><th>Review</th></tr></thead><tbody>{apps.map(a=><tr key={a.id}><td><b>{a.sellerName}</b><small>{a.email}<br/>{a.country}</small></td><td><span className={a.kycStatus==="verified"?"admin-status admin-status-success":"admin-status admin-status-warning"}>{a.kycStatus||"none"} · L{a.kycLevel??0}</span></td><td><span className="admin-status">{a.status}</span></td><td><small>{new Date(a.createdAt).toLocaleString()}</small></td><td><button className="admin-btn admin-btn-soft" onClick={()=>setSelected(a)}>View</button></td></tr>)}</tbody></table>{!apps.length&&<div className="admin-empty">No seller applications.</div>}</div>}</section>
  <section className="cp-card cp-card-pad"><div className="admin-card-title"><div><span className="cp-kicker">APPROVED SELLERS</span><h2>Sellers</h2><p>These email addresses have seller access.</p></div><Check size={20}/></div><div className="admin-mini-list">{sellers.map(s=><div key={s.userId}><span><b>{s.sellerName}</b><small>{s.email} · {s.country}</small></span><div className="admin-actions"><span className="admin-status admin-status-success">Active</span><button className="admin-btn admin-btn-danger" disabled={busy} onClick={()=>void dismissSeller(s)}><UserX size={14}/> Dismiss</button></div></div>)}{!sellers.length&&<div className="admin-empty">No approved sellers yet.</div>}</div></section></div>
  <section className="cp-card cp-card-pad" style={{marginTop:18}}><div className="admin-card-title"><div><span className="cp-kicker">PAYOUTS</span><h2>Seller withdrawals</h2><p>Review requests, send the bank payout, then mark the request paid.</p></div><DollarSign size={20}/></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Seller</th><th>Amount</th><th>Bank</th><th>Status</th><th>Requested</th><th>Action</th></tr></thead><tbody>{withdrawals.map(w=><tr key={w.id}><td><b>{w.sellerName||"Seller #"+w.userId}</b><small>{w.email}</small></td><td><b>₦{Number(w.amount).toLocaleString()}</b></td><td><b>{w.bankName}</b><small>{w.accountName}<br/>{w.accountNumber}</small></td><td><span className="admin-status">{w.status}</span></td><td><small>{new Date(w.createdAt).toLocaleString()}</small></td><td><div className="admin-actions"><button className="admin-btn admin-btn-soft" disabled={busy||w.status!=="pending"} onClick={()=>void reviewWithdrawal(w.id,"approved")}>Approve</button><button className="admin-btn admin-btn-danger" disabled={busy||["declined","paid"].includes(w.status)} onClick={()=>void reviewWithdrawal(w.id,"declined")}>Decline</button><button className="admin-btn admin-btn-primary" disabled={busy||w.status!=="approved"} onClick={()=>void reviewWithdrawal(w.id,"paid")}>Mark paid</button></div></td></tr>)}</tbody></table>{!withdrawals.length&&<div className="admin-empty">No seller withdrawal requests.</div>}</div></section>
 </section>;
}
