import { Check, Clock3, ShieldCheck, UserX, X } from "lucide-react";
import { useEffect, useState } from "react";
import { apiUrl } from "./page-api";

async function adminRequest<T>(path:string,token:string,options:any={}):Promise<T>{
 const r=await fetch(apiUrl(path),{method:options.method||"GET",headers:{Authorization:"Bearer "+token,...(options.body?{"Content-Type":"application/json"}:{})},body:options.body?JSON.stringify(options.body):undefined});
 const p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.error||"Admin request failed.");return p;
}
export default function AdminSellers({token,onNotice,onError}:{token:string;onNotice:(s:string)=>void;onError:(s:string)=>void}){
 const [apps,setApps]=useState<any[]>([]),[sellers,setSellers]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{const [a,s]=await Promise.all([adminRequest<any>("/api/admin/seller-applications",token),adminRequest<any>("/api/admin/sellers",token)]);setApps(a.data||[]);setSellers(s.data||[])}catch(e:any){onError(e?.message||"Seller data could not be loaded.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const review=async(id:number,status:"approved"|"declined"|"reviewing")=>{setBusy(true);try{await adminRequest("/api/admin/seller-applications/"+id,token,{method:"PATCH",body:{status}});setSelected(null);onNotice(status==="approved"?"Seller approved and access granted.":status==="declined"?"Seller application declined.":"Application moved to review.");await load()}catch(e:any){onError(e?.message||"Seller review failed.")}finally{setBusy(false)}};
 return <section className="admin-section">
  {selected&&<div className="admin-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="cp-card cp-card-pad admin-detail-modal"><div className="admin-panel-head"><div><span className="cp-kicker">SELLER APPLICATION</span><h2>{selected.sellerName}</h2><p>{selected.email} · User #{selected.userId}</p></div><button className="admin-btn admin-btn-soft" onClick={()=>setSelected(null)}><X size={15}/></button></div><div className="admin-detail-facts"><span><small>Status</small><b>{selected.status}</b></span><span><small>KYC</small><b>{selected.kycStatus} · L{selected.kycLevel??0}</b></span><span><small>Legal name</small><b>{selected.legalName}</b></span><span><small>Phone</small><b>{selected.phone}</b></span><span><small>Country</small><b>{selected.country}</b></span><span><small>Address</small><b>{selected.address}</b></span><span><small>Account source</small><b>{selected.accountSource}</b></span><span><small>Experience</small><b>{selected.experience||"—"}</b></span><span><small>Application IP</small><b className="admin-mono">{selected.applicationIp||"—"}</b></span><span><small>Device / browser</small><b>{selected.userAgent||"—"}</b></span><span><small>Submitted</small><b>{new Date(selected.createdAt).toLocaleString()}</b></span></div><div className="admin-actions" style={{justifyContent:"flex-end",marginTop:18}}><button className="admin-btn admin-btn-soft" disabled={busy} onClick={()=>void review(selected.id,"reviewing")}><Clock3 size={14}/> Reviewing</button><button className="admin-btn admin-btn-danger" disabled={busy} onClick={()=>void review(selected.id,"declined")}><UserX size={14}/> Decline</button><button className="admin-btn admin-btn-primary" disabled={busy} onClick={()=>void review(selected.id,"approved")}><Check size={14}/> Approve seller</button></div></section></div>}
  <div className="admin-grid-two"><section className="cp-card cp-card-pad"><div className="admin-card-title"><div><span className="cp-kicker">SELLER QUEUE</span><h2>Applications</h2><p>KYC-verified users requesting marketplace selling access.</p></div><ShieldCheck size={20}/></div>{loading?<div className="admin-empty">Loading seller applications…</div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Applicant</th><th>KYC</th><th>Status</th><th>Submitted</th><th>Review</th></tr></thead><tbody>{apps.map(a=><tr key={a.id}><td><b>{a.sellerName}</b><small>{a.email}<br/>{a.country}</small></td><td><span className={a.kycStatus==="verified"?"admin-status admin-status-success":"admin-status admin-status-warning"}>{a.kycStatus||"none"} · L{a.kycLevel??0}</span></td><td><span className="admin-status">{a.status}</span></td><td><small>{new Date(a.createdAt).toLocaleString()}</small></td><td><button className="admin-btn admin-btn-soft" onClick={()=>setSelected(a)}>View</button></td></tr>)}</tbody></table>{!apps.length&&<div className="admin-empty">No seller applications.</div>}</div>}</section>
  <section className="cp-card cp-card-pad"><div className="admin-card-title"><div><span className="cp-kicker">APPROVED SELLERS</span><h2>Sellers</h2><p>These email addresses have seller access.</p></div><Check size={20}/></div><div className="admin-mini-list">{sellers.map(s=><div key={s.userId}><span><b>{s.sellerName}</b><small>{s.email} · {s.country}</small></span><span className="admin-status admin-status-success">Active</span></div>)}{!sellers.length&&<div className="admin-empty">No approved sellers yet.</div>}</div></section></div>
 </section>;
}
