import { Check, ExternalLink, Instagram, PackagePlus, RefreshCw, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { apiUrl } from "./page-api";

const PLATFORMS=[["instagram","Instagram"],["tiktok","TikTok"],["facebook","Facebook"],["discord","Discord"],["twitter","X / Twitter"],["youtube","YouTube"],["telegram","Telegram"],["snapchat","Snapchat"],["linkedin","LinkedIn"]];
const logos:any={instagram:"https://cdn.simpleicons.org/instagram",tiktok:"https://cdn.simpleicons.org/tiktok",facebook:"https://cdn.simpleicons.org/facebook",discord:"https://cdn.simpleicons.org/discord",twitter:"https://cdn.simpleicons.org/x",youtube:"https://cdn.simpleicons.org/youtube",telegram:"https://cdn.simpleicons.org/telegram",snapchat:"https://cdn.simpleicons.org/snapchat",linkedin:"https://cdn.simpleicons.org/linkedin"};
async function request<T>(path:string,token:string,options:any={}){const r=await fetch(apiUrl(path),{...options,headers:{...(options.body?{"Content-Type":"application/json"}:{}),Authorization:"Bearer "+token}});const j=await r.json().catch(()=>null);if(!r.ok)throw new Error(j?.error||"Request failed");return j as T}
export default function AdminSocialAccounts(){
 const token=typeof window==="undefined"?"":localStorage.getItem("cipherpay_token")||sessionStorage.getItem("cipherpay_admin_token")||"";
 const [inventory,setInventory]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[form,setForm]=useState({platform:"instagram",country:"Nigeria",title:"",price:"",accounts:""}),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const load=async()=>{if(!token)return;try{const [a,b]=await Promise.all([request<any>("/api/admin/social-accounts/inventory",token),request<any>("/api/admin/social-account-requests",token)]);setInventory(a.data||[]);setRequests(b.data||[])}catch(e:any){setNotice(e?.message||"Could not load account inventory.")}};
 useEffect(()=>{void load()},[]);
 const upload=async(e:any)=>{e.preventDefault();setBusy(true);setNotice("");try{const r=await request<any>("/api/admin/social-accounts/inventory/bulk",token,{method:"POST",body:JSON.stringify(form)});setForm({...form,title:"",price:"",accounts:""});setNotice((r.added||0)+" accounts added to inventory.");await load()}catch(e:any){setNotice(e?.message||"Upload failed.")}finally{setBusy(false)}};
 const remove=async(id:number)=>{if(!confirm("Remove this unsold account from inventory?"))return;try{await request("/api/admin/social-accounts/inventory/"+id,token,{method:"DELETE"});await load()}catch(e:any){setNotice((e as Error).message)}};
 const status=async(id:number,value:string)=>{try{await request("/api/admin/social-account-requests/"+id,token,{method:"PATCH",body:JSON.stringify({status:value})});await load()}catch(e:any){setNotice((e as Error).message)}};
 const available=inventory.filter(x=>x.status==="available").length;
 return <section className="admin-section">
  <section className="cp-card cp-card-pad"><div className="admin-card-title"><div><span className="cp-kicker">SOCIAL ACCOUNT MARKET</span><h2>Upload account inventory</h2><p>Choose the platform and country, set the selling price, then paste one account per line. Credentials are encrypted before storage.</p></div><PackagePlus size={20}/></div>
   <form className="cp-form admin-form" onSubmit={upload}><div className="admin-form-row"><label className="cp-field"><span>Platform</span><select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}>{PLATFORMS.map(p=><option value={p[0]} key={p[0]}>{p[1]}</option>)}</select></label><label className="cp-field"><span>Country</span><input value={form.country} onChange={e=>setForm({...form,country:e.target.value})} placeholder="Nigeria" required/></label></div><div className="admin-form-row"><label className="cp-field"><span>Listing / account type</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Instagram aged account" required/></label><label className="cp-field"><span>Price per account (NGN)</span><input type="number" min="1" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="5000" required/></label></div><label className="cp-field"><span>Account logs — one per line</span><textarea rows={7} value={form.accounts} onChange={e=>setForm({...form,accounts:e.target.value})} placeholder={"username|password|email|emailPassword|2FA|recovery"} required/></label><small className="admin-muted">Maximum 500 accounts per upload. Keep the same six-field order on each line.</small><div style={{marginTop:14}}><AdminButtonShim disabled={busy}>{busy?"Uploading…":"Upload inventory"} <PackagePlus size={15}/></AdminButtonShim></div></form>{notice&&<div className="cp-notice cp-notice-success admin-notice">{notice}</div>}</section>
  <section className="cp-card cp-card-pad"><div className="admin-card-title"><div><span className="cp-kicker">LIVE STOCK</span><h2>{available} accounts available</h2><p>Sold units remain in the audit trail but cannot be purchased again.</p></div><RefreshCw size={20}/></div><div className="admin-social-inventory">{inventory.slice(0,100).map(x=><div className="admin-social-row" key={x.id}><img src={logos[x.platform]} alt=""/><div><b>{x.title}</b><small>{x.platform} · {x.country} · ₦{Number(x.price).toLocaleString("en-NG")}</small></div><span className={x.status==="available"?"admin-social-stock":"admin-social-sold"}>{x.status==="available"?"Available":"Sold"}</span>{x.status==="available"&&<button type="button" onClick={()=>void remove(x.id)}><Trash2 size={14}/></button>}</div>)}{!inventory.length&&<div className="admin-empty">No account inventory yet.</div>}</div></section>
  <section className="cp-card cp-card-pad"><div className="admin-card-title"><div><span className="cp-kicker">SPECIAL REQUESTS</span><h2>Customer requests</h2><p>Use support chat, email, or Telegram to follow up with customers.</p></div><ExternalLink size={20}/></div><div className="admin-social-requests">{requests.map(r=><div className="admin-social-request" key={r.id}><div><b>{r.platform}{r.country?" · "+r.country:""}</b><small>{r.firstName||""} {r.lastName||""} · {r.email}</small><p>{r.description}</p>{r.contactValue&&<small>Preferred contact: {r.contactMethod} · {r.contactValue}</small>}</div><div className="admin-social-request-actions"><select value={r.status} onChange={e=>void status(r.id,e.target.value)}><option value="new">New</option><option value="contacted">Contacted</option><option value="fulfilled">Fulfilled</option><option value="closed">Closed</option></select>{r.contactMethod==="email"&&r.contactValue&&<a href={"mailto:"+r.contactValue}>Email</a>}{r.contactMethod==="telegram"&&r.contactValue&&<a href={"https://t.me/"+r.contactValue.replace(/^@/,"")} target="_blank" rel="noreferrer">Telegram</a>}<a href="/admin?tab=support">Support</a></div></div>)}{!requests.length&&<div className="admin-empty">No special requests yet.</div>}</div></section>
 </section>
}
function AdminButtonShim({children,disabled}:{children:any,disabled?:boolean}){return <button type="submit" className="admin-btn admin-btn-primary" disabled={disabled}>{children}</button>}
