import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronRight, Clapperboard, Cloud, Film, FolderOpen, Gauge, Layers3, Link2, Play, Plus, Radio, RefreshCw, Sparkles, WandSparkles, Zap } from "lucide-react";
import { useLocation } from "wouter";
import { apiRequest } from "./page-api";

type Project={id:number;title:string;prompt:string|null;status:string;durationSec:number;createdAt:string;updatedAt:string};
type Job={id:number;projectId:number;type:string;status:string;progress:number;createdAt:string};
type Overview={credits:number;projects:Project[];jobs:Job[];channels:any[];schedules:any[];assets:any[];stats:{projects:number;generations:number;channels:number;scheduled:number;assets:number}};

const nav:any[]=[["command","Command Center",Gauge],["studio","AI Studio",Sparkles],["projects","Projects",FolderOpen],["assets","Assets",Layers3],["scheduler","Scheduler",CalendarDays],["channels","Channels",Radio],["billing","Credits",Zap]];

export default function KlipHubPage(){
 const [,setLocation]=useLocation();
 const [overview,setOverview]=useState<Overview|null>(null); const [tab,setTab]=useState("command");
 const [selected,setSelected]=useState<Project|null>(null); const [title,setTitle]=useState(""); const [prompt,setPrompt]=useState(""); const [duration,setDuration]=useState(30);
 const [creating,setCreating]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{document.body.classList.add("kliphub-mode");return()=>document.body.classList.remove("kliphub-mode")},[]);
 const load=async()=>{setLoading(true);try{setOverview(await apiRequest<Overview>("/api/kliphub/overview"));setError("")}catch(e:any){setError(e?.message||"KlipHub could not load.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{if(!title.trim()||!prompt.trim())return;setCreating(true);try{const r=await apiRequest<{projectId:number}>("/api/kliphub/projects",{method:"POST",body:{title:title.trim(),prompt:prompt.trim(),durationSec:duration}});setTitle("");setPrompt("");setTab("projects");await load();const d=await apiRequest<{project:Project}>("/api/kliphub/projects/"+r.projectId);setSelected(d.project)}catch(e:any){setError(e?.message||"Could not create the video.")}finally{setCreating(false)}};
 const queue=async(id:number)=>{try{await apiRequest("/api/kliphub/projects/"+id+"/jobs",{method:"POST",body:{type:"scene_video"}});await load()}catch(e:any){setError(e?.message||"Could not queue generation.")}};
 const projects=overview?.projects||[]; const jobs=overview?.jobs||[];
 const headings:any={command:["COMMAND CENTER","Your creative operation, in one place."],studio:["AI STUDIO","Turn a brief into a production-ready video."],projects:["PROJECTS","Every idea, scene and generation stays organized."],assets:["ASSETS","Your creative library, ready when you are."],scheduler:["SCHEDULER","Plan the drop before the render finishes."],channels:["CHANNELS","Connect the destinations for your content."],billing:["CREDITS","One balance for your KlipHub production engine."]};
 const h=headings[tab]||headings.command;
 return <div className="kh-app"><aside className="kh-sidebar"><div className="kh-brand"><button onClick={()=>setLocation("/")} className="kh-brand-mark">CP</button><div><b>Klip<span>Hub</span></b><small>CREATIVE ENGINE</small></div></div><div className="kh-switcher"><span>WORKSPACE</span><button onClick={()=>setLocation("/")}><i>CP</i><div><b>CipherPay</b><small>Finance & services</small></div><ArrowLeft size={15}/></button><div className="kh-current"><i>KH</i><div><b>KlipHub</b><small>AI video studio</small></div><Check size={15}/></div></div><nav className="kh-nav"><span>CREATE</span>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={17}/><span>{label}</span>{id==="studio"&&<em>NEW</em>}</button>)}</nav><div className="kh-sidebar-card"><Sparkles size={18}/><b>Production engine</b><p>Build scenes, queue generations and keep every release organized.</p><button onClick={()=>setTab("studio")}>Create a video <ArrowRight size={14}/></button></div></aside>
 <main className="kh-main"><header className="kh-topbar"><div className="kh-breadcrumb"><span>KlipHub</span><ChevronRight size={14}/><b>{h[0]}</b></div><div className="kh-top-actions"><div className="kh-credit-pill"><Zap size={14}/><b>{(overview?.credits||3000).toLocaleString()}</b><span>credits</span></div><button className="kh-icon-btn" onClick={()=>void load()}><RefreshCw size={17}/></button><button className="kh-cipher-btn" onClick={()=>setLocation("/")}><span>CP</span> Switch to CipherPay <ArrowLeft size={14}/></button></div></header><div className="kh-content">{error&&<div className="kh-error">{error}<button onClick={()=>setError("")}>Dismiss</button></div>}<div className="kh-page-head"><div><span className="kh-eyebrow">{h[0]}</span><h1>{h[1]}</h1></div>{tab!=="studio"&&<button className="kh-primary" onClick={()=>setTab("studio")}><Plus size={17}/> New video</button>}</div>{loading&&!overview?<div className="kh-loading"><RefreshCw className="kh-spin"/><span>Loading your creative workspace…</span></div>:<>{tab==="command"&&<Command o={overview!} projects={projects} jobs={jobs} studio={()=>setTab("studio")} open={p=>{setSelected(p);setTab("projects")}}/>}{tab==="studio"&&<Studio title={title} setTitle={setTitle} prompt={prompt} setPrompt={setPrompt} duration={duration} setDuration={setDuration} creating={creating} create={create}/>} {tab==="projects"&&<Projects projects={projects} active={selected||projects[0]||null} open={setSelected} queue={queue}/>} {tab==="assets"&&<Library title="ASSET LIBRARY" icon={Layers3} count={(overview?.assets||[]).length} text="Uploads, references, thumbnails and generated media will live here."/>}{tab==="scheduler"&&<Library title="PUBLISHING CALENDAR" icon={CalendarDays} count={(overview?.schedules||[]).length} text="Schedule completed projects once your distribution channels are connected."/>}{tab==="channels"&&<Library title="DISTRIBUTION" icon={Link2} count={(overview?.channels||[]).length} text="Bring your publishing destinations into KlipHub."/>}{tab==="billing"&&<Credits credits={overview?.credits||3000} jobs={jobs}/>}</>}</div></main></div>
}

function Command(p:{o:Overview;projects:Project[];jobs:Job[];studio:()=>void;open:(p:Project)=>void}){return <div className="kh-command"><section className="kh-hero"><div className="kh-hero-copy"><span className="kh-eyebrow">KLIPHUB / PRODUCTION OS</span><h2>Make the idea.<br/><em>Then make it move.</em></h2><p>AI-assisted video production built around projects, scenes, assets, schedules and distribution.</p><div className="kh-hero-actions"><button className="kh-primary" onClick={p.studio}><WandSparkles size={17}/> Start creating</button><button className="kh-ghost">View recent work <ArrowRight size={15}/></button></div></div><div className="kh-hero-orbit"><div className="kh-orbit o1"/><div className="kh-orbit o2"/><div className="kh-orbit-core"><Film size={31}/><span>AI</span></div></div></section><div className="kh-stat-grid"><Stat label="Projects" value={p.o.stats.projects} icon={FolderOpen}/><Stat label="Generations" value={p.o.stats.generations} icon={Clapperboard}/><Stat label="Scheduled" value={p.o.stats.scheduled} icon={CalendarDays}/><Stat label="Credits" value={p.o.credits.toLocaleString()} icon={Zap}/></div><section className="kh-section"><div className="kh-section-head"><div><span>WORKSPACE</span><h3>Recent projects</h3></div><button onClick={p.studio}>New project <Plus size={14}/></button></div>{p.projects.length?<div className="kh-project-grid">{p.projects.slice(0,6).map(x=><ProjectCard key={x.id} project={x} onClick={()=>p.open(x)}/>)}</div>:<Empty title="Your first video starts here." detail="Give KlipHub a brief and it will build the production structure for you." action={p.studio}/>}</section><section className="kh-section"><div className="kh-section-head"><div><span>ACTIVITY</span><h3>Generation queue</h3></div></div>{p.jobs.length?<div className="kh-queue">{p.jobs.slice(0,6).map(j=><div className="kh-queue-row" key={j.id}><span className="kh-queue-icon"><Film size={15}/></span><div><b>{j.type.replaceAll("_"," ")}</b><small>Project #{j.projectId}</small></div><strong>{j.status}</strong><small>{new Date(j.createdAt).toLocaleString()}</small></div>)}</div>:<Empty title="Nothing in the queue." detail="Generate a scene from any project and it will appear here." action={p.studio}/>}</section></div>}
function Studio(p:any){return <div className="kh-studio"><section className="kh-studio-main"><div className="kh-studio-intro"><span className="kh-eyebrow">AI PRODUCTION / 01</span><h2>Describe what you want<br/><em>to see.</em></h2><p>KlipHub turns your brief into a structured sequence of scenes you can refine and generate.</p></div><label><span>PROJECT NAME</span><input value={p.title} onChange={(e)=>p.setTitle(e.target.value)} placeholder="e.g. Summer campaign — Lagos"/></label><label><span>CREATIVE BRIEF</span><textarea value={p.prompt} onChange={(e)=>p.setPrompt(e.target.value)} placeholder="Describe the story, subject, camera language, mood and what the viewer should feel…" rows={8}/></label><div className="kh-duration"><span>DURATION</span><div>{[30,60,120].map((v)=><button key={v} className={p.duration===v?"active":""} onClick={()=>p.setDuration(v)}>{v===120?"2 min":v+" sec"}</button>)}</div></div><button className="kh-primary kh-create" disabled={p.creating||!p.title.trim()||!p.prompt.trim()} onClick={p.create}>{p.creating?<><RefreshCw className="kh-spin"/> Building production plan…</>:<><Sparkles size={17}/> Build my video <ArrowRight size={17}/></>}</button></section><aside className="kh-studio-preview"><span>LIVE PREVIEW / AI PLAN</span><div><Play size={22}/><b>YOUR STORY</b><small>Production preview</small></div><p>01 · Brief analysis<br/>02 · Scene planning<br/>03 · Generation</p></aside></div>}
function Projects(p:{projects:Project[];active:Project|null;open:(x:Project)=>void;queue:(id:number)=>void}){return <div className="kh-projects"><div className="kh-project-grid kh-project-grid-large">{p.projects.map(x=><ProjectCard key={x.id} project={x} onClick={()=>p.open(x)}/>)}</div>{p.active&&<section className="kh-project-inspector"><div><span className="kh-eyebrow">SELECTED PROJECT</span><h2>{p.active.title}</h2><p>{p.active.prompt}</p></div><div><span>{p.active.durationSec}s · {p.active.status}</span><button className="kh-primary" onClick={()=>p.queue(p.active!.id)}><Clapperboard size={16}/> Generate scene</button></div></section>}</div>}
function ProjectCard(p:{project:Project;onClick:()=>void}){return <button className="kh-project-card" onClick={p.onClick}><div className="kh-project-art"><div className="kh-art-mark"><Film size={25}/><span>#{String(p.project.id).padStart(2,"0")}</span></div><span>{p.project.durationSec}s</span></div><div className="kh-project-info"><div><b>{p.project.title}</b><small>{p.project.status}</small></div><p>{p.project.prompt}</p><div>Updated {new Date(p.project.updatedAt).toLocaleDateString()} <ChevronRight size={14}/></div></div></button>}
function Library(p:any){const Icon=p.icon;return <section className="kh-empty-section"><div className="kh-large-icon"><Icon size={28}/></div><span className="kh-eyebrow">{p.title}</span><h2>{p.count?p.count+" ready in your workspace.":"The workspace is ready."}</h2><p>{p.text}</p><button className="kh-ghost"><Cloud size={16}/> Coming online with your first release</button></section>}
function Credits(p:{credits:number;jobs:Job[]}){return <section className="kh-credit-page"><div className="kh-credit-hero"><div><span className="kh-eyebrow">KLIPHUB CREDITS</span><h2>{p.credits.toLocaleString()}</h2><p>Available production credits. Your CipherPay account remains the identity layer across both products.</p></div><div><Zap size={34}/></div></div>{p.jobs.map(j=><div className="kh-usage-row" key={j.id}><Film size={15}/><span>{j.type}</span><b>{j.status}</b><small>{new Date(j.createdAt).toLocaleString()}</small></div>)}</section>}
function Stat(p:{label:string;value:any;icon:any}){const Icon=p.icon;return <div className="kh-stat"><span><Icon size={16}/></span><small>{p.label}</small><b>{p.value}</b></div>}
function Empty(p:{title:string;detail:string;action:()=>void}){return <div className="kh-empty"><Sparkles size={19}/><b>{p.title}</b><p>{p.detail}</p><button onClick={p.action}>Start creating <ArrowRight size={14}/></button></div>}