import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, Check, Clapperboard, Film, FolderOpen, Gauge, ImageIcon, Layers3, Link2, Play, Plus, Radio, RefreshCw, Sparkles, WandSparkles, Zap } from "lucide-react";
import { apiRequest } from "./page-api";
import { generateLocalImage, detectLocalImageEngine } from "../lib/kliphub-local-image";

type Project={id:number;title:string;prompt:string|null;status:string;durationSec:number;createdAt:string;updatedAt:string};
type Job={id:number;projectId:number;type:string;status:string;progress:number;createdAt:string};
type Overview={credits:number;projects:Project[];jobs:Job[];channels:any[];schedules:any[];assets:any[];stats:{projects:number;generations:number;channels:number;scheduled:number;assets:number}};

const nav:any[]=[["command","Command Center",Gauge],["studio","AI Studio",Sparkles],["projects","Projects",FolderOpen],["assets","Assets",Layers3],["scheduler","Scheduler",CalendarDays],["channels","Channels",Radio],["billing","Credits",Zap]];

export default function KlipHubPage(){
 const [overview,setOverview]=useState<Overview|null>(null);
 const [tab,setTab]=useState("command");
 const [selected,setSelected]=useState<Project|null>(null);
 const [title,setTitle]=useState(""); const [prompt,setPrompt]=useState(""); const [duration,setDuration]=useState(30);
 const [creating,setCreating]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [generating,setGenerating]=useState(false); const [generationStatus,setGenerationStatus]=useState("");
 const load=async()=>{setLoading(true);try{setOverview(await apiRequest<Overview>("/api/kliphub/overview"));setError("")}catch(e:any){setError(e?.message||"KlipHub could not load.")}finally{setLoading(false)}};
 useEffect(()=>{void load(); const timer=window.setInterval(()=>void load(),3000); return ()=>window.clearInterval(timer)},[]);
 const create=async()=>{if(!title.trim()||!prompt.trim())return;setCreating(true);try{const r=await apiRequest<{projectId:number}>("/api/kliphub/projects",{method:"POST",body:{title:title.trim(),prompt:prompt.trim(),durationSec:duration}});setTitle("");setPrompt("");setTab("projects");await load();const d=await apiRequest<{project:Project}>("/api/kliphub/projects/"+r.projectId);setSelected(d.project)}catch(e:any){setError(e?.message||"Could not create the video.")}finally{setCreating(false)}};
 const queue=async(id:number,type="scene_video")=>{if(type!=="image"){setError("Real video generation is not enabled on the CPU-only server yet. I removed the fake renderer instead of pretending it was AI.");return} setGenerating(true);setGenerationStatus("Checking your browser GPU…");try{const caps=await detectLocalImageEngine();if(!caps.webgpu)throw new Error("Your browser does not expose WebGPU. Open KlipHub in a WebGPU-capable browser.");setGenerationStatus("Loading the real SD-Turbo model into your device…");const project=projects.find(p=>p.id===id);if(!project)throw new Error("Project not found.");const out=await generateLocalImage(project.prompt||project.title,p=>setGenerationStatus(p.message||p.phase||"Generating…"));setGenerationStatus("Saving generated image…");const dataUrl=await new Promise<string>((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.onerror=()=>reject(new Error("Could not read generated image."));fr.readAsDataURL(out.blob)});await apiRequest("/api/kliphub/assets",{method:"POST",body:{projectId:id,dataUrl,name:"kliphub-"+Date.now()+".png"}});await load();setGenerationStatus("Done.");}catch(e:any){setError(e?.message||"Real local image generation failed.");setGenerationStatus("")}finally{setGenerating(false)}};
 const projects=overview?.projects||[]; const jobs=overview?.jobs||[];
 const headings:any={command:["KLIPHUB / COMMAND CENTER","Your creative workspace, without the clutter."],studio:["KLIPHUB / AI STUDIO","Turn a brief into a production-ready video."],projects:["KLIPHUB / PROJECTS","Every idea, scene and generation in one place."],assets:["KLIPHUB / ASSETS","Your creative library, ready when you are."],scheduler:["KLIPHUB / SCHEDULER","Plan the release before the render finishes."],channels:["KLIPHUB / CHANNELS","Connect the destinations for your content."],billing:["KLIPHUB / CREDITS","Your production balance, at a glance."]};
 const h=headings[tab]||headings.command;
 return <div className="kh-workspace">
   <div className="kh-topline"><div><span className="kh-eyebrow">{h[0]}</span><h1>{h[1]}</h1></div><div className="kh-actions"><div className="kh-credit-pill"><Zap size={14}/><b>{(overview?.credits||3000).toLocaleString()}</b><span>credits</span></div><button className="kh-icon-btn" onClick={()=>void load()} aria-label="Refresh KlipHub"><RefreshCw size={16}/></button><button className="kh-icon-btn kh-reset-btn" onClick={async()=>{if(!confirm("Delete all your KlipHub projects, jobs, scenes and generated assets?"))return;try{await apiRequest("/api/kliphub/reset",{method:"DELETE"});setSelected(null);await load()}catch(e:any){setError(e?.message||"Could not reset KlipHub.")}}} title="Reset KlipHub">Reset</button><button className="kh-new-btn" onClick={()=>setTab("studio")}><Plus size={16}/> New video</button></div></div>
   {error&&<div className="kh-error">{error}<button onClick={()=>setError("")}>Dismiss</button></div>}
   {generating&&<div className="kh-generation-bar"><RefreshCw className="kh-spin" size={15}/><span>{generationStatus}</span></div>}<div className="kh-tabs" role="tablist">{nav.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={15}/><span>{label}</span>{id==="studio"&&<em>NEW</em>}</button>)}</div>
   {loading&&!overview?<div className="kh-loading"><RefreshCw className="kh-spin"/><span>Loading your creative workspace…</span></div>:<>{tab==="command"&&<Command o={overview!} projects={projects} jobs={jobs} studio={()=>setTab("studio")} open={p=>{setSelected(p);setTab("projects")}}/>}{tab==="studio"&&<Studio title={title} setTitle={setTitle} prompt={prompt} setPrompt={setPrompt} duration={duration} setDuration={setDuration} creating={creating} create={create}/>} {tab==="projects"&&<Projects projects={projects} active={selected||projects[0]||null} jobs={jobs} queue={queue} generating={generating}/>} {tab==="assets"&&<AssetsLibrary assets={overview?.assets||[]}/>}{tab==="scheduler"&&<Library title="PUBLISHING CALENDAR" icon={CalendarDays} count={(overview?.schedules||[]).length} text="Schedule completed projects once your distribution channels are connected."/>}{tab==="channels"&&<Library title="DISTRIBUTION" icon={Link2} count={(overview?.channels||[]).length} text="Bring your publishing destinations into KlipHub."/>}{tab==="billing"&&<Credits credits={overview?.credits||3000} jobs={jobs}/>}</>}
 </div>;
}

function Command(p:{o:Overview;projects:Project[];jobs:Job[];studio:()=>void;open:(p:Project)=>void}){return <div className="kh-command">
 <section className="kh-hero"><div className="kh-hero-copy"><span className="kh-kicker"><Sparkles size={13}/> AI VIDEO PRODUCTION</span><h2>Ideas in.<br/><span>Videos out.</span></h2><p>Plan, create and organize your AI video projects from the same polished workspace you already use for CipherPay.</p><div className="kh-hero-actions"><button className="kh-primary" onClick={p.studio}><WandSparkles size={17}/> Start creating</button><button className="kh-secondary" onClick={()=>document.querySelector(".kh-projects-anchor")?.scrollIntoView({behavior:"smooth"})}>View projects <ArrowRight size={15}/></button></div></div><div className="kh-visual"><div className="kh-orbit kh-orbit-one"/><div className="kh-orbit kh-orbit-two"/><div className="kh-video-card"><div className="kh-video-card-top"><span>KLIPHUB</span><span>AI / 01</span></div><div className="kh-video-screen"><Play size={24}/><span>CREATIVE PREVIEW</span></div><div className="kh-video-card-bottom"><b>Production ready</b><small>Scenes · Assets · Distribution</small></div></div></div></section>
 <div className="kh-stat-grid"><Stat label="Projects" value={p.o.stats.projects} icon={FolderOpen}/><Stat label="Generations" value={p.o.stats.generations} icon={Clapperboard}/><Stat label="Scheduled" value={p.o.stats.scheduled} icon={CalendarDays}/><Stat label="Credits" value={p.o.credits.toLocaleString()} icon={Zap}/></div>
 <section className="kh-section kh-projects-anchor"><div className="kh-section-head"><div><span>WORKSPACE</span><h3>Recent projects</h3></div><button onClick={p.studio}>New project <Plus size={14}/></button></div>{p.projects.length?<div className="kh-project-grid">{p.projects.slice(0,6).map(x=><ProjectCard key={x.id} project={x} onClick={()=>p.open(x)}/>)}</div>:<Empty title="Your first video starts here." detail="Give KlipHub a brief and it will build the production structure for you." action={p.studio}/>}</section>
 <section className="kh-section"><div className="kh-section-head"><div><span>ACTIVITY</span><h3>Generation queue</h3></div></div>{p.jobs.length?<div className="kh-queue">{p.jobs.slice(0,6).map(j=><div className="kh-queue-row" key={j.id}><span className="kh-queue-icon"><Film size={15}/></span><div><b>{j.type.replaceAll("_"," ")}</b><small>Project #{j.projectId}</small></div><strong>{j.status}</strong><small>{new Date(j.createdAt).toLocaleString()}</small></div>)}</div>:<Empty title="Nothing in the queue." detail="Generate a scene from any project and it will appear here." action={p.studio}/>}</section>
 </div>}

function Studio(p:any){return <div className="kh-studio"><section className="kh-panel kh-studio-main"><div className="kh-studio-intro"><span className="kh-kicker"><WandSparkles size={12}/> AI PRODUCTION / 01</span><h2>Describe what you want<br/><span>to see.</span></h2><p>KlipHub turns your brief into a structured sequence of scenes you can refine and generate.</p></div><label><span>PROJECT NAME</span><input value={p.title} onChange={(e)=>p.setTitle(e.target.value)} placeholder="e.g. Summer campaign — Lagos"/></label><label><span>CREATIVE BRIEF</span><textarea value={p.prompt} onChange={(e)=>p.setPrompt(e.target.value)} placeholder="Describe the story, subject, camera language, mood and what the viewer should feel…" rows={8}/></label><div className="kh-duration"><span>DURATION</span><div>{[30,60,120].map((v:number)=><button type="button" key={v} className={p.duration===v?"active":""} onClick={()=>p.setDuration(v)}>{v===120?"2 min":v+" sec"}</button>)}</div></div><button type="button" className="kh-primary kh-create" disabled={p.creating||!p.title.trim()||!p.prompt.trim()} onClick={p.create}>{p.creating?<><RefreshCw className="kh-spin"/> Building production plan…</>:<><Sparkles size={17}/> Build my video <ArrowRight size={17}/></>}</button></section><aside className="kh-panel kh-studio-preview"><span className="kh-preview-label">LIVE PREVIEW</span><div className="kh-preview-screen"><Play size={22}/><b>YOUR STORY</b><small>Production preview</small></div><div className="kh-preview-steps"><span><b>01</b> Brief analysis</span><span><b>02</b> Scene planning</span><span><b>03</b> Generation</span></div></aside></div>}

function Projects(p:{projects:Project[];active:Project|null;queue:(id:number,type?:string)=>void;jobs:Job[]}){const activeJobs=p.active?p.jobs.filter(j=>j.projectId===p.active!.id):[];return <div className="kh-projects"><div className="kh-project-grid kh-project-grid-large">{p.projects.map(x=><ProjectCard key={x.id} project={x} onClick={()=>p.active?.id===x.id?undefined:undefined}/>)}</div>{p.active&&<section className="kh-panel kh-project-inspector"><div><span className="kh-eyebrow">SELECTED PROJECT</span><h2>{p.active.title}</h2><p>{p.active.prompt}</p></div><div><span>{p.active.durationSec}s · {p.active.status}</span><div className="kh-inspector-actions"><button className="kh-primary" onClick={()=>p.queue(p.active!.id,"scene_video")} disabled={activeJobs.some(j=>j.status==="queued"||j.status==="processing")}><Clapperboard size={16}/> {activeJobs.some(j=>j.status==="processing")?"Processing…":"Test video"}</button><button className="kh-secondary" onClick={()=>p.queue(p.active!.id,"image")} disabled={activeJobs.some(j=>j.status==="queued"||j.status==="processing")}><ImageIcon size={16}/> {activeJobs.some(j=>j.status==="processing")?"Generating…":"Test image"}</button></div>{activeJobs.slice(0,3).map(j=><div className="kh-job-progress" key={j.id}><div><b>{j.type}</b><span>{j.status==="completed"?"Complete":j.status==="failed"?"Failed":j.status==="processing"?"Processing":"Queued"}</span></div><div className="kh-progress-track"><i style={{width:`${Math.max(4,j.progress||0)}%`}}/></div>{j.error&&<small>{j.error}</small>}</div>)}</div></section>}</div>}

function ProjectCard(p:{project:Project;onClick:()=>void}){return <button type="button" className="kh-project-card" onClick={p.onClick}><div className="kh-project-art"><div className="kh-art-mark"><Film size={24}/><span>#{String(p.project.id).padStart(2,"0")}</span></div><span>{p.project.durationSec}s</span></div><div className="kh-project-info"><div><b>{p.project.title}</b><small>{p.project.status}</small></div><p>{p.project.prompt}</p><div>Updated {new Date(p.project.updatedAt).toLocaleDateString()} <ArrowRight size={13}/></div></div></button>}

function AssetsLibrary(p:{assets:any[]}){return <section className="kh-assets-library"><div className="kh-section-head"><div><span>KLIPHUB OUTPUTS</span><h3>Generated media</h3></div><span className="kh-asset-count">{p.assets.length} asset{p.assets.length===1?"":"s"}</span></div>{p.assets.length?<div className="kh-assets-grid">{p.assets.map((a:any)=><article className="kh-asset-card" key={a.id}><div className="kh-asset-preview">{a.type==="video"?<video src={a.url} controls preload="metadata"/>:<img src={a.url} alt={a.name}/>}</div><div className="kh-asset-meta"><b>{a.name}</b><small>{a.type} · Project #{a.projectId||"—"}</small></div></article>)}</div>:<div className="kh-panel kh-empty-section"><div className="kh-large-icon"><Layers3 size={28}/></div><span className="kh-eyebrow">ASSET LIBRARY</span><h2>Your generated media will appear here.</h2><p>Run the local CPU image test first. Video generation is also available as a small test render.</p></div>}</section>}

function Library(p:any){const Icon=p.icon;return <section className="kh-panel kh-empty-section"><div className="kh-large-icon"><Icon size={28}/></div><span className="kh-eyebrow">{p.title}</span><h2>{p.count?p.count+" ready in your workspace.":"The workspace is ready."}</h2><p>{p.text}</p><button type="button" className="kh-secondary"><Layers3 size={15}/> Coming online with your first release</button></section>}

function Credits(p:{credits:number;jobs:Job[]}){return <section className="kh-credits"><div className="kh-credit-hero"><div><span className="kh-eyebrow">KLIPHUB CREDITS</span><h2>{p.credits.toLocaleString()}</h2><p>Available production credits shared with your creative workspace.</p></div><div className="kh-credit-orb"><Zap size={30}/></div></div>{p.jobs.map(j=><div className="kh-usage-row" key={j.id}><Film size={15}/><span>{j.type}</span><b>{j.status}</b><small>{new Date(j.createdAt).toLocaleString()}</small></div>)}</section>}

function Stat(p:{label:string;value:any;icon:any}){const Icon=p.icon;return <div className="kh-stat"><span><Icon size={16}/></span><small>{p.label}</small><b>{p.value}</b></div>}
function Empty(p:{title:string;detail:string;action:()=>void}){return <div className="kh-empty"><Sparkles size={19}/><b>{p.title}</b><p>{p.detail}</p><button type="button" onClick={p.action}>Start creating <ArrowRight size={14}/></button></div>}
