import { Check, DollarSign, PackagePlus, ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { apiRequest } from "./page-api";
import "./seller.css";

const PLATFORMS=[
 {id:"instagram",name:"Instagram"},{id:"tiktok",name:"TikTok"},{id:"facebook",name:"Facebook"},
 {id:"discord",name:"Discord"},{id:"twitter",name:"X / Twitter"},{id:"youtube",name:"YouTube"},
 {id:"telegram",name:"Telegram"},{id:"snapchat",name:"Snapchat"},{id:"linkedin",name:"LinkedIn"},
 {id:"email",name:"Email"}
];

export default function SellerPage(){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [form,setForm]=useState({platform:"instagram",country:"",title:"",price:"",username:"",password:"",email:"",emailPassword:"",twoFactor:"",recovery:""});
 const [saving,setSaving]=useState(false);
 const [withdrawOpen,setWithdrawOpen]=useState(false),[withdrawSaving,setWithdrawSaving]=useState(false),[bankVerifying,setBankVerifying]=useState(false),[banks,setBanks]=useState<any[]>([]),[verifiedBank,setVerifiedBank]=useState<any>(null);
 const [withdrawForm,setWithdrawForm]=useState({amount:"",bankCode:"",bankName:"",accountNumber:"",accountName:"",narration:"",pin:""});
 const load=async()=>{setLoading(true);try{setData(await apiRequest<any>("/api/seller/dashboard"));setError("")}catch(e:any){setError(e?.message||"Seller access could not be loaded.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(withdrawOpen){void apiRequest<any>("/api/seller/banks").then(r=>setBanks(r.data||[])).catch(()=>setBanks([]))}},[withdrawOpen]);
 useEffect(()=>{document.body.style.overflow=withdrawOpen?"hidden":"";return()=>{document.body.style.overflow=""}},[withdrawOpen]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");setNotice("");try{await apiRequest("/api/seller/listings",{method:"POST",body:{platform:form.platform,country:form.country,title:form.title,price:Number(form.price),username:form.username,details:{username:form.username,password:form.password,email:form.email,emailPassword:form.emailPassword,twoFactor:form.twoFactor,recovery:form.recovery}}});setForm({platform:"instagram",country:"",title:"",price:"",username:"",password:"",email:"",emailPassword:"",twoFactor:"",recovery:""});setNotice("Account added to the marketplace.");await load()}catch(e:any){setError(e?.message||"Could not add the account.")}finally{setSaving(false)}};
 const remove=async(id:number)=>{try{await apiRequest("/api/seller/listings/"+id,{method:"DELETE"});await load()}catch(e:any){setError(e?.message||"Could not remove the listing.")}};
 const verifyBank=async()=>{if(!withdrawForm.bankCode||withdrawForm.accountNumber.length!==10){setError("Select your bank and enter the 10-digit account number.");return}setBankVerifying(true);setError("");setVerifiedBank(null);try{const r=await apiRequest<any>("/api/seller/verify-bank",{method:"POST",body:{bankCode:withdrawForm.bankCode,accountNumber:withdrawForm.accountNumber}});setVerifiedBank(r);setWithdrawForm(v=>({...v,bankName:banks.find((b:any)=>String(b.code)===String(v.bankCode))?.name||"",accountName:r.accountName}))}catch(e:any){setError(e?.message||"Could not verify that account.")}finally{setBankVerifying(false)}};
 const requestWithdrawal=async(e:FormEvent)=>{e.preventDefault();if(!verifiedBank){setError("Verify your bank account first.");return}setWithdrawSaving(true);setError("");setNotice("");try{await apiRequest("/api/seller/withdrawals",{method:"POST",body:{...withdrawForm,amount:Number(withdrawForm.amount),verifiedAccountName:verifiedBank.accountName}});setWithdrawForm({amount:"",bankCode:"",bankName:"",accountNumber:"",accountName:"",narration:"",pin:""});setVerifiedBank(null);setWithdrawOpen(false);setNotice("Withdrawal request submitted. Your funds are held while the request is reviewed.");await load()}catch(e:any){setError(e?.message||"Could not submit the withdrawal request.")}finally{setWithdrawSaving(false)}};
 if(loading)return <div className="seller-page"><div className="seller-empty">Loading seller dashboard…</div></div>;
 return <div className="seller-page">
  <section className="seller-hero"><div><span className="seller-kicker">CIPHERPAY / SELLER</span><h1>Sell social & email accounts.</h1><p>List your account inventory, reach CipherPay buyers, and receive your share automatically when an account sells.</p></div><div className="seller-fee"><DollarSign size={18}/><b>{data?.feeRate ?? 5}%</b><span>platform share per sale</span></div></section>
  {error&&<div className="seller-notice error">{error}</div>}{notice&&<div className="seller-notice success">{notice}</div>}
  <section className="seller-card seller-withdraw-card"><div className="seller-card-head"><div><span className="seller-kicker">WITHDRAW YOUR EARNINGS</span><h2>Request a withdrawal</h2><p>Your seller earnings are added to your CipherPay balance. Request a bank payout when you're ready; funds are held while the request is reviewed.</p></div><DollarSign size={20}/></div><div className="seller-withdraw-summary"><div><small>Available balance</small><b>₦{Number(data?.walletBalance??0).toLocaleString()}</b></div><div><small>Pending withdrawal</small><b>₦{Number(data?.pendingWithdrawal??0).toLocaleString()}</b></div><div><small>Minimum</small><b>₦1,000</b></div></div><button className="seller-primary seller-withdraw-btn" onClick={()=>setWithdrawOpen(true)} disabled={Number(data?.walletBalance??0)<1000}>Request bank withdrawal</button></section>
  {withdrawOpen&&<div className="seller-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget){setWithdrawOpen(false);setVerifiedBank(null)}}}><section className="seller-modal"><div className="seller-card-head"><div><span className="seller-kicker">BANK PAYOUT</span><h2>Request withdrawal</h2><p>Enter your bank details. We'll verify the account name before you confirm the payout.</p></div><button className="seller-close" type="button" aria-label="Close" onClick={()=>{setWithdrawOpen(false);setVerifiedBank(null)}}>×</button></div><form onSubmit={requestWithdrawal} className="seller-form"><label>Amount (₦)<input required type="number" min="1000" step="0.01" max={Number(data?.walletBalance??0)} value={withdrawForm.amount} onChange={e=>setWithdrawForm({...withdrawForm,amount:e.target.value})} placeholder="10000"/></label><label>Bank<select required value={withdrawForm.bankCode} onChange={e=>{setVerifiedBank(null);const b=banks.find((x:any)=>String(x.code)===e.target.value);setWithdrawForm({...withdrawForm,bankCode:e.target.value,bankName:b?.name||"",accountName:""})}}><option value="">Select your bank</option>{banks.map((b:any)=><option key={b.code} value={b.code}>{b.name}</option>)}</select></label><label>Account number<input required inputMode="numeric" maxLength={10} value={withdrawForm.accountNumber} onChange={e=>{setVerifiedBank(null);setWithdrawForm({...withdrawForm,accountNumber:e.target.value.replace(/\D/g,"")})}} placeholder="0123456789"/></label>{!verifiedBank?<button type="button" className="seller-secondary" onClick={()=>void verifyBank()} disabled={bankVerifying||!withdrawForm.bankCode||withdrawForm.accountNumber.length!==10}>{bankVerifying?"Verifying account…":"Verify bank account"}</button>:<div className="seller-bank-verified"><small>ACCOUNT VERIFIED</small><b>{verifiedBank.accountName}</b><span>{withdrawForm.bankName} · {verifiedBank.accountNumber}</span><label className="seller-confirm"><input type="checkbox" required/> <span>Yes, this is the bank account I want to withdraw to.</span></label></div>}<label>Note (optional)<input value={withdrawForm.narration} onChange={e=>setWithdrawForm({...withdrawForm,narration:e.target.value})} placeholder="Optional payout note"/></label><label>4-digit transfer PIN<input required inputMode="numeric" maxLength={4} type="password" value={withdrawForm.pin} onChange={e=>setWithdrawForm({...withdrawForm,pin:e.target.value.replace(/\D/g,"").slice(0,4)})} placeholder="••••"/></label><button className="seller-primary" disabled={withdrawSaving||!verifiedBank}>{withdrawSaving?"Submitting…":"Confirm withdrawal request"}</button></form></section></div>}
  <div className="seller-grid">
   <section className="seller-card"><div className="seller-card-head"><div><span className="seller-kicker">01 / LIST INVENTORY</span><h2>Add an account or email</h2><p>Credentials are encrypted before storage. Buyers only receive details after purchase.</p></div><PackagePlus size={20}/></div>
    <form onSubmit={submit} className="seller-form">
     <div className="seller-row"><label>Platform<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}>{PLATFORMS.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Country<input required value={form.country} onChange={e=>setForm({...form,country:e.target.value})} placeholder="Nigeria"/></label></div>
     <label>Listing title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Instagram aged account"/></label>
     <label>Price (₦)<input required type="number" min="1" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="5000"/></label>
     <div className="seller-row"><label>{form.platform==="email"?"Email address":"Username"}<input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>{form.platform==="email"?"Email password":"Password"}<input required value={form.password} onChange={e=>setForm({...form,password:e.target.value})} type="password"/></label></div>
     <div className="seller-row"><label>{form.platform==="email"?"Recovery email":"Account email"}<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>{form.platform==="email"?"Recovery email password":"Email password"}<input value={form.emailPassword} onChange={e=>setForm({...form,emailPassword:e.target.value})} type="password"/></label></div>
     <div className="seller-row"><label>2FA / backup code<input value={form.twoFactor} onChange={e=>setForm({...form,twoFactor:e.target.value})}/></label><label>Recovery details<input value={form.recovery} onChange={e=>setForm({...form,recovery:e.target.value})}/></label></div>
     <button className="seller-primary" disabled={saving}>{saving?"Adding…":"Publish account"} <Check size={16}/></button>
    </form>
   </section>
   <aside className="seller-side"><div className="seller-stat"><small>Available listings</small><b>{data?.stats?.available ?? 0}</b></div><div className="seller-stat"><small>Sold listings</small><b>{data?.stats?.sold ?? 0}</b></div><div className="seller-trust"><ShieldCheck size={18}/><div><b>Seller protection</b><p>Your KYC-backed seller identity is tied to every listing. CipherPay keeps {data?.feeRate ?? 5}% and credits the remainder after a completed sale.</p></div></div></aside>
  </div>
  <section className="seller-card seller-listings"><div className="seller-card-head"><div><span className="seller-kicker">02 / YOUR INVENTORY</span><h2>Listings & sales</h2></div></div>
   <div className="seller-list">{(data?.listings??[]).map((item:any)=><div className="seller-list-row" key={item.id}><div><b>{item.title}</b><span>{item.platform} · {item.country} · ₦{Number(item.price).toLocaleString("en-NG",{minimumFractionDigits:2})}</span></div><span className={"seller-status "+item.status}>{item.status}</span>{item.status==="available"&&<button type="button" onClick={()=>void remove(item.id)}><Trash2 size={15}/></button>}</div>)}{!(data?.listings??[]).length&&<div className="seller-empty">No listings yet.</div>}</div>
   <div className="seller-sales"><h3>Withdrawal requests</h3>{(data?.withdrawals||[]).map((w:any)=><div className="seller-sale-row" key={w.id}><span><b>₦{Number(w.amount).toLocaleString()}</b><small>{w.bankName} · {String(w.accountNumber).replace(/\d(?=\d{4})/g,"•")} · {new Date(w.createdAt).toLocaleDateString()}</small></span><span className={"seller-status "+w.status}>{w.status}</span></div>)}{!(data?.withdrawals||[]).length&&<div className="seller-empty">No withdrawal requests yet.</div>}</div>
  <div className="seller-sales"><h3>Recent sales</h3>{(data?.sales??[]).map((sale:any)=><div className="seller-sale-row" key={sale.id}><span>{sale.platform} · {sale.country}</span><b>₦{Number(sale.sellerNet).toLocaleString("en-NG",{minimumFractionDigits:2})}</b><small>{sale.feeRate}% fee</small></div>)}{!(data?.sales??[]).length&&<div className="seller-empty">No sales yet.</div>}</div>
  </section>
 </div>
}
