import { Check, ChevronDown, Clipboard, Copy, MessageCircle, Search, Send, ShoppingBag } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { apiRequest } from "./page-api";
import "./social-accounts.css";

const PLATFORMS=[
 {id:"instagram",name:"Instagram",short:"IG",logo:"https://cdn.simpleicons.org/instagram"},
 {id:"tiktok",name:"TikTok",short:"TK",logo:"https://cdn.simpleicons.org/tiktok"},
 {id:"facebook",name:"Facebook",short:"FB",logo:"https://cdn.simpleicons.org/facebook"},
 {id:"discord",name:"Discord",short:"DC",logo:"https://cdn.simpleicons.org/discord"},
 {id:"twitter",name:"X / Twitter",short:"X",logo:"https://cdn.simpleicons.org/x"},
 {id:"youtube",name:"YouTube",short:"YT",logo:"https://cdn.simpleicons.org/youtube"},
 {id:"telegram",name:"Telegram",short:"TG",logo:"https://cdn.simpleicons.org/telegram"},
 {id:"snapchat",name:"Snapchat",short:"SC",logo:"https://cdn.simpleicons.org/snapchat"},
 {id:"linkedin",name:"LinkedIn",short:"IN",logo:"https://cdn.simpleicons.org/linkedin"}
];
const money=(v:any)=>"₦"+Number(v||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2});
const meta=(id:string)=>PLATFORMS.find(p=>p.id===String(id||"").trim().toLowerCase());
const logoFallback=(e:React.SyntheticEvent<HTMLImageElement>)=>{e.currentTarget.style.display="none";e.currentTarget.parentElement?.classList.add("logo-fallback")};

export default function SocialAccountsPage(){
 const [catalog,setCatalog]=useState<any[]>([]),[orders,setOrders]=useState<any[]>([]),[platform,setPlatform]=useState("all"),[country,setCountry]=useState("all"),[query,setQuery]=useState("");
 const [selected,setSelected]=useState<any>(null),[purchase,setPurchase]=useState<any>(null),[details,setDetails]=useState<any>(null),[requestOpen,setRequestOpen]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [request,setRequest]=useState({platform:"",country:"",description:"",budget:"",contactMethod:"support",contactValue:""});
 const load=async()=>{setLoading(true);setMessage("");try{const a=await apiRequest<any>("/api/social-accounts/catalog");setCatalog(a.data||[]);try{const b=await apiRequest<any>("/api/social-accounts/orders");setOrders(b.data||[])}catch{setOrders([])}}catch(e:any){setMessage(e?.message||"We could not load the account inventory. Please try again.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{document.body.style.overflow=requestOpen?"hidden":"";return()=>{document.body.style.overflow=""}},[requestOpen]);
 const countries=useMemo(()=>Array.from(new Set(catalog.map(x=>String(x.country||"").trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b)),[catalog]);
 const filtered=useMemo(()=>catalog.filter(x=>{
 const xp=String(x.platform||"").trim().toLowerCase(), xc=String(x.country||"").trim();
 return (platform==="all"||xp===platform)&&(country==="all"||xc===country)&&(!query.trim()||(String(x.title||"")+" "+xp+" "+xc).toLowerCase().includes(query.trim().toLowerCase()));
}),[catalog,platform,country,query]);
 const buy=async()=>{if(!selected)return;setBusy(true);try{const r=await apiRequest<any>("/api/social-accounts/purchase/"+selected.listingId,{method:"POST"});setPurchase(r);setSelected(null);await load()}catch(e:any){setMessage(e?.message||"Purchase failed.")}finally{setBusy(false)}};
 const reveal=async(id:number)=>{setBusy(true);try{const r=await apiRequest<any>("/api/social-accounts/orders/"+id+"/reveal",{method:"POST"});setDetails(r.data);setPurchase(null)}catch(e:any){setMessage(e?.message||"Could not unlock details.")}finally{setBusy(false)}};
 const submitRequest=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await apiRequest("/api/social-accounts/requests",{method:"POST",body:JSON.stringify(request)});setRequestOpen(false);setRequest({platform:"",country:"",description:"",budget:"",contactMethod:"support",contactValue:""});setMessage("Special request received.")}catch(e:any){setMessage(e?.message||"Request failed.")}finally{setBusy(false)}};
 return <div className="social-account-page">
  <section className="social-account-hero"><div><span className="social-account-eyebrow">SOCIAL ACCOUNTS</span><h1>Buy social media accounts.</h1><p>Choose an available account by platform and country, pay from your CipherPay balance, and receive the account details immediately after purchase.</p><div className="social-account-hero-actions"><button onClick={()=>setRequestOpen(true)}><MessageCircle size={16}/> Request a special account</button><a href="#account-orders"><ShoppingBag size={16}/> My purchases</a></div></div><div className="social-account-hero-orb"><div className="social-orb-grid">{PLATFORMS.slice(0,6).map(p=><img key={p.id} src={p.logo} alt={p.name} onError={logoFallback}/>)}</div><b>LIVE INVENTORY</b><span>Real-time stock</span></div></section>
  <section className="social-account-toolbar"><div className="social-platform-pills"><button className={platform==="all"?"active":""} onClick={()=>setPlatform("all")}>All</button>{PLATFORMS.map(p=><button key={p.id} className={platform===p.id?"active":""} onClick={()=>setPlatform(p.id)}><img src={p?.logo} alt={p?.name||item.platform} onError={logoFallback}/>{p.name}</button>)}</div><div className="social-account-filters"><label><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search accounts"/></label><select value={country} onChange={e=>setCountry(e.target.value)}><option value="all">All countries</option>{countries.map(c=><option key={c}>{c}</option>)}</select></div></section>
  {message&&<div className="social-account-message">{message}</div>}
  <section className="social-account-grid">{loading?<div className="social-account-empty">Loading live inventory…</div>:filtered.length?filtered.map(item=>{const p=meta(item.platform),stock=Number(item.stock||0);return <article className="social-account-card" key={item.platform+"-"+item.country+"-"+item.title}><div className="social-card-top"><div className="social-brand-mark"><img src={p?.logo} alt=""/><span>{p?.short}</span></div><span className={"social-stock "+(stock?"in":"out")}>{stock?stock+" in stock":"Out of stock"}</span></div><div className="social-card-country">{item.country}</div><h2>{item.title}</h2><p>Secure checkout · Instant delivery · {p?.name||item.platform}</p><div className="social-card-bottom"><div><small>From</small><strong>{money(item.price)}</strong></div><button disabled={!stock} onClick={()=>setSelected(item)}>{stock?"Buy account":"Sold out"}<Send size={15}/></button></div></article>;}):<div className="social-account-empty"><ShoppingBag size={25}/><b>No accounts match.</b><span>Try another filter or request a special account.</span></div>}</section>
  <section className="social-special-banner"><div><span>CAN'T FIND WHAT YOU NEED?</span><h2>Request another platform or country.</h2><p>Send the exact requirements to the CipherPay team.</p></div><button onClick={()=>setRequestOpen(true)}>Make a special request <ChevronDown size={16}/></button></section>
  <section id="account-orders" className="social-account-orders"><div className="social-section-head"><span>YOUR PURCHASES</span><h2>Account orders</h2></div>{orders.length?orders.map(o=><div className="social-order-card" key={o.id}><div><b>{meta(o.platform)?.name||o.platform}</b><span>{o.country} · {o.title} · {money(o.amount)}</span></div><span className="social-order-status">Delivered</span><button onClick={()=>setPurchase({order:o})}>Review details</button></div>):<div className="social-account-empty">No account purchases yet.</div>}</section>
  {selected&&<div className="social-modal-backdrop"><div className="social-modal"><div className="social-modal-icon"><ShoppingBag size={20}/></div><span className="social-modal-kicker">CHECKOUT</span><h2>Buy this account?</h2><p>{meta(selected.platform)?.name||selected.platform} · {selected.country}</p><div className="social-review-line"><span>{selected.title}</span><strong>{money(selected.price)}</strong></div><small>Your wallet is debited only after you confirm.</small><div className="social-modal-actions"><button className="ghost" onClick={()=>setSelected(null)}>Cancel</button><button onClick={()=>void buy()} disabled={busy}>{busy?"Processing…":"Confirm & pay"}</button></div></div></div>}
  {purchase&&<div className="social-modal-backdrop"><div className="social-modal"><div className="social-modal-icon"><Check size={20}/></div><span className="social-modal-kicker">PURCHASE COMPLETE</span><h2>Payment received.</h2><p>Your account is reserved. Confirm to review the account details.</p><div className="social-review-line"><span>{purchase.order?.title}</span><strong>{money(purchase.order?.amount)}</strong></div><div className="social-modal-actions"><button className="ghost" onClick={()=>setPurchase(null)}>Close</button><button onClick={()=>void reveal(purchase.order.id)} disabled={busy}>{busy?"Unlocking…":"Review account details"}</button></div></div></div>}
  {details&&<div className="social-modal-backdrop"><div className="social-modal"><div className="social-modal-icon"><Clipboard size={20}/></div><span className="social-modal-kicker">DELIVERY</span><h2>Account details</h2><p>Keep these credentials private.</p><div className="social-detail-list">{Object.entries(details.details||{}).filter(([,v])=>v).map(([k,v])=><div key={k}><span>{k.replaceAll(/([A-Z])/g," $1")}</span><b>{String(v)}</b><button onClick={()=>void navigator.clipboard?.writeText(String(v))}><Copy size={14}/></button></div>)}</div><button className="social-close-wide" onClick={()=>setDetails(null)}>Done</button></div></div>}
  {requestOpen&&<div className="social-modal-backdrop"><form className="social-modal" onSubmit={submitRequest}><div className="social-modal-icon"><MessageCircle size={20}/></div><span className="social-modal-kicker">SPECIAL REQUEST</span><h2>Can't find your platform?</h2><p>Tell us what you need and how to contact you.</p><div className="social-request-grid"><label>Platform<input value={request.platform} onChange={e=>setRequest({...request,platform:e.target.value})} placeholder="e.g. Reddit, Twitch" required/></label><label>Country<input value={request.country} onChange={e=>setRequest({...request,country:e.target.value})} placeholder="Country"/></label><label>Budget<input type="number" min="0" value={request.budget} onChange={e=>setRequest({...request,budget:e.target.value})} placeholder="Optional"/></label><label>Contact<select value={request.contactMethod} onChange={e=>setRequest({...request,contactMethod:e.target.value})}><option value="support">Support chat</option><option value="email">Email</option><option value="telegram">Telegram</option></select></label><label className="wide">Contact value<input value={request.contactValue} onChange={e=>setRequest({...request,contactValue:e.target.value})} placeholder="Email or @username"/></label><label className="wide">Requirements<textarea value={request.description} onChange={e=>setRequest({...request,description:e.target.value})} placeholder="Account type, country, profile requirements, quantity…" required/></label></div><div className="social-modal-actions"><button type="button" className="ghost" onClick={()=>setRequestOpen(false)}>Cancel</button><button type="submit" disabled={busy}>{busy?"Sending…":"Send request"}</button></div></form></div>}
 </div>
}