import { pgTable, serial, integer, text, timestamp, numeric } from "drizzle-orm/pg-core";

export const giftCardOrdersTable = pgTable("gift_card_orders", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  productId: integer("product_id").notNull(),
  productName: text("product_name").notNull(),
  countryCode: text("country_code").notNull(),
  currencyCode: text("currency_code").notNull(),
  unitPrice: numeric("unit_price", { precision: 18, scale: 2 }).notNull(),
  quantity: integer("quantity").notNull().default(1),
  amountPaidNgn: numeric("amount_paid_ngn", { precision: 18, scale: 2 }).notNull(),
  recipientEmail: text("recipient_email").notNull(),
  status: text("status").notNull().default("pending"),
  redemptionCode: text("redemption_code"),
  pin: text("pin"),
  externalTransactionId: text("external_transaction_id"),
  transactionId: integer("transaction_id"),
  logoUrl: text("logo_url"),
  sogoReference: text("sogo_reference"),
  sogoTransactionId: text("sogo_transaction_id"),
  payoutAmountNgn: numeric("payout_amount_ngn", { precision: 18, scale: 2 }),
  feeNgn: numeric("fee_ngn", { precision: 18, scale: 2 }).default("0"),
  netPayoutNgn: numeric("net_payout_ngn", { precision: 18, scale: 2 }),
  payoutDestination: text("payout_destination").notNull().default("wallet"),
  payoutAccountId: integer("payout_account_id"),
  payoutAccountName: text("payout_account_name"),
  payoutAccountNumber: text("payout_account_number"),
  payoutBankName: text("payout_bank_name"),
  adminId: integer("admin_id"),
  processingStartedAt: timestamp("processing_started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  failureReason: text("failure_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type GiftCardOrder = typeof giftCardOrdersTable.$inferSelect;
